# Site
name: "HMJ Lab"
title: "Hub for Media and Journalism Lab"
description: "Innovating media and journalism through cutting-edge research and collaboration."
logo: 'assets/images/hmj_logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: pdharry@gmail.com

# Authors
authors:
  Harry:
    name: Harry
    display_name: Harry
    avatar: 'assets/images/avatar-sal.png'
    email: pdharry@gmail.com
    web: https://www.wowthemes.net/donate/
    instagram: https://instagram.com/luckypd
    description: "방송노동자, 역시 무엇이든 시작하고 보는 맛"
  Juan:
    name: Juan
    display_name: Juan    
    avatar: 'assets/images/avatar.png'
    email: pdharry@gmail.com
    web: https://www.wowthemes.net
    instagram: https://instagram.com/luckypd
    description: "노래부르기를 좋아아하는 대안학교 고등학생"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
